version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  gestaopedidos_db:
    image: postgres:16
    container_name: gestaopedidos_db
    environment:
      POSTGRES_DB: gestaopedidos_db
      POSTGRES_USER: gestaopedidos
      POSTGRES_PASSWORD: gestaopedidos
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  gestaopedidos_app:
    build: .
    container_name: gestaopedidos_app
    depends_on:
      - gestaopedidos_db
      - kafka
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://gestaopedidos_db:5432/gestaopedidos_db
      SPRING_DATASOURCE_USERNAME: gestaopedidos
      SPRING_DATASOURCE_PASSWORD: gestaopedidos
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

volumes:
  db_data:
