CREATE TABLE parceiro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    limite_credito NUMERIC(19, 2) NOT NULL
);

CREATE TABLE pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parceiro_id BIGINT NOT NULL,
    valor_total NUMERIC(19, 2) NOT NULL,
    status VARCHAR(255) NOT NULL,
    data_criacao TIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP NOT NULL,
    CONSTRAINT fk_parceiro FOREIGN KEY (parceiro_id) REFERENCES parceiro(id)
);

CREATE TABLE item_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto VARCHAR(255) NOT NULL,
    quantidade INTEGER NOT NULL,
    preco_unitario NUMERIC(19, 2) NOT NULL,
    pedido_id BIGINT NOT NULL,
    CONSTRAINT fk_pedido FOREIGN KEY (pedido_id) REFERENCES pedido(id)
);
